【FE課題】BooklogのStep1
NBphamngocha/dept_design_fe_work01 pull request #1
Opened 2023-10-23 03:04 UTC by NBphamngocha

Step1の実装が完了しました。PRをご確認お願いします。
## Issueリンク
https://github.com/newbeescoltd/nb_study_react/issues/4

2023-10-23 05:36 UTC, NBmaeda requested changes
かなり細かいところまで指摘して恐縮ですが、フロントエンド開発において重要な点も含んでいます。
ご質問があればいつでもお待ちしていますので、じっくり取り組んでみてください🙏

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/index.module.css
ファイル名を`index.module.css`としていますが、`App.tsx`から読み込んでいます。
特に意図がなければ対応関係がわかりやすいように、`.tsx`ファイルと名称を統一して`App.module.css`とした方が良いと思います。

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/index.module.css
> +}
この箇所をはじめとして、アンダースコアから始まるスタイルはどのhtml要素にも適用されていないかと思います。
Reactによって出力されたcssをそのままコピペで使用するのではなく、スタイルとhtml要素との対応関係を考慮してスタイルの整理をした方が良いと思います。

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const [bookData, setBookData] = useState(MOCK_DATA.items)
9行目ではジェネリクスを利用した宣言を行なっているため、8行目でもジェネリクスを利用して型を明示して宣言してみてください。
現在の状態では一見しても`bookData`の型がわかりづらいため、型を明示することは可読性を高める助けになります。

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const [book, setBook] = useState<BookItem>(bookData[0])
8行目で宣言した`bookData`の1つ目の要素を、改めて別のstate変数として宣言しています。
これは特別な意図がない場合は、冗長な実装となってしまいます。

state変数が多くなるとパフォーマンスに影響がある他、管理するstateが増えて状態管理が難しくなります。そのため、stateはよりシンプルにまとめる方が良いと思います。

9行目は無くても問題ないと思うので、もう一度見直してみてください。

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const { id, volumeInfo } = book;
変数`id`は使用していないため、宣言の必要はないと思います。また簡潔に書くのであれば、11行目で`title`等の各変数に分割代入を行っているため、`volumeInfo`も宣言は必要ないと思います。
「変数の型を明示すること」「どうやったら不必要な変数の宣言を避けられるか」の2点を考慮して修正してみてください。

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/App.tsx
> +    window.open(`${previewLink}`, '_blank');
関数`handleBookLink`は必要でしょうか？
html要素だけで実現できる処理をJavaScriptで実装するのは冗長ですし、この実装だとポップアップがブロックされている場合はリンクが開けない可能性があります。

この関数を使用せずに意図した処理を実現する方法を、もう一度考えてみてください。

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/App.tsx
> +          <img src={imageLinks?.thumbnail} alt="React.js&Next.js超入門第2版" />
`imageLinks`が`undefined`の場合、`<img src="undefined" alt="React.js&Next.js超入門第2版" />`要素が出力されてしまい、好ましくない表示となります。

`imageLinks`をはじめ`undefined`になる可能性がある変数に関しては、**変数に値が代入されている場合のみ**各要素が表示されるように記述をしてください。

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/App.tsx
> +          <p>著者:<span>{authors}</span></p>
`authors`の型は`string[] | undefined`です。著者が`['掌田津耶乃', 'エビスコム']`のように複数の場合は、以下のように出力されます。

著者:掌田津耶乃エビスコム

これでは正しい情報が伝わりにくくなるため、配列を処理するための実装を行なってください。

2023-10-23 05:36 UTC, NBmaeda commented on booklog/src/App.tsx
> +          <button className={styles.boxButton} onClick={handleBookLink}>詳しく見る</button>
上記の`handleBookLink`の箇所でも伝えましたが、button要素の`onClick`を使用してページのリンクを行うことはできるだけ避けた方がいいです。
MDNの[a要素の項](https://developer.mozilla.org/ja/docs/Web/HTML/Element/a)を見ると、以下のように記載してあります。
>href 属性を用いて、別のウェブページ、ファイル、メールアドレス、同一ページ内の場所、または他の URL へのハイパーリンクを作成します。

これを用いた方がHTMLの意味的にも正しく、冗長なJavaScriptでの実装も避けられるため良いかと思います。

2023-10-26 02:21 UTC, NBmaeda requested changes
概ね問題ない形に修正できていると思います👌
ただ1点、気になる点があったので修正をお願いします。

2023-10-26 02:21 UTC, NBmaeda commented on booklog/src/App.tsx
> +            previewLink && <button className={styles.boxButton}><a href={previewLink} target="_blank">詳しく見る</a></button>
この行の記述に関して、MDNの[bottun要素のページ](https://developer.mozilla.org/ja/docs/Web/HTML/Element/button)を見てみましょう。
「許可されている内容」を確認すると、以下のようになっています。
>[記述コンテンツ](https://developer.mozilla.org/ja/docs/Web/HTML/Content_categories#%E8%A8%98%E8%BF%B0%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84)、但し[対話型コンテンツ](https://developer.mozilla.org/ja/docs/Web/HTML/Content_categories#%E5%AF%BE%E8%A9%B1%E5%9E%8B%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84)があってはならない

「記述コンテンツ」および「対話型コンテンツ」の両方を確認すると、a要素は「記述コンテンツだけを含む場合」に記述コンテンツとしてみなされますが、同時に対話型コンテンツでもあります。
つまり34行目でbutton要素の内容としてa要素を使用していますが、これはhtmlの仕様としては正しくない記述となります。

これにより意図しない挙動を起こす、あるいは意図した挙動が起こらないなどの影響が考えられるため、不具合を防止するためにもhtml要素の仕様を確認する癖をつけた方がいいと思います。
基本的には[MDN](https://developer.mozilla.org/ja/docs/Web)や[HTML Living Standard](https://html.spec.whatwg.org/)を確認すると、だいたいの仕様は確認できると思います。

今一度、仕様に則った形でこの行を修正してみてください。

2023-10-27 06:26 UTC, NBphamngocha commented on booklog/src/App.tsx
> +            previewLink && <button className={styles.boxButton}><a href={previewLink} target="_blank">詳しく見る</a></button>
@NBmaeda
毎回毎回丁寧に教えていただき、ありがとうございました。大変勉強になりました📝
damさんのご指定通り、 不具合が発生する原因なるためbutton要素の中にaタグを入れてはいけないですね！
html要素の仕様を事前にちゃんと確認できずうっかりしてコードを書きました。以降気をつけております！！

修正しましたので、お手隙の際またご確認お願いします🙇‍♀️

2023-10-27 07:49 UTC, NBmaeda approved these changes
細かいところまで、ご対応ありがとうございます！
問題ないと思います🎉

ただ1点だけ気になるとすれば、今回の修正箇所の`a`要素を`p`要素で囲んでいる点です。
特にスタイリングに利用している訳でもなさそうですし、html要素の役割的にも囲む必要はないと思っています。

htmlの構造的に大きな問題がある訳ではないのですが、htmlはあくまでも「Hyper**Text Markup** Language」です。
ブラウザに文章の意味や構造を正しく伝えるためにも、あるいは多人数開発を考慮して可読性を上げるためにも、「適切に」「簡潔な」htmlを書くということを意識するとより良くなると思います💡

ひとまずStep1お疲れ様でした！
次のStepも頑張ってください😌

2023-10-27 08:07 UTC, merged