【FE課題】BooklogのStep2
NBphamngocha/dept_design_fe_work01 pull request #2
Opened 2023-10-31 06:32 UTC by NBphamngocha

## Issueリンク
https://github.com/newbeescoltd/nb_study_react/issues/5
## Step1のデザイン
http://127.0.0.1:4173/steps/step2/

2023-10-31 10:38 UTC, NBmaeda requested changes
Step1での学びを糧に、Step2では良い点がいくつもありました！
しっかり自習をされているんだなということを感じます😌

ですが、より良くできるポイントもいくつか見つかりました。
また細かい指摘も多く恐縮ですが、1つ1つその指摘の背景も理解できるように修正に取り組んでみてください！

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/App.module.css
>    margin-bottom: .6em
101行目や116行目等も含め、他の行には存在する「末尾のセミコロン(trailing semicolon)」がありません。
特にcssに関しては、セミコロンを付けるように統一するのが好ましいです。

理由としては、cssでは各クラスの最終行以外のプロパティにセミコロンが存在しない場合、エラーが発生するためです。
例えばセミコロンが付いていない行があった場合、プロパティをコピー＆ペーストした際に予期せぬ不具合が発生する場合があります。

これらの記述の規則に関しては、前回のワークショップでも説明しましたが一般的に「Prettier」等のツールを使用して統一しています。
当リポジトリでも`dept_design_fe_work01/`の`.prettierrc.json`や`devcontainer.json`を反映してコンテナの再ビルドを行うと、各ファイルの保存時にPrettierが自動で走るようになると思います。
上記ファイルも含め、`dept_design_fe_work01/`の設定ファイルが全て反映されるように修正をお願いします。

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/App.tsx
> +const App = (): JSX.Element => {
戻り値の型、`JSX.Element`を宣言するように修正したのは非常に良いと思います🙆
型推論に任せることもできますが、明示することでコード全体の見通しが良くなったり、作業者の意図が伝わりやすくなります。
面倒ですが積極的に行っていきましょう。

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/App.tsx
> +      <Header />
Headerを別コンポーネントに切り分けたのはGoodです👍
ひとまず最初は「どの箇所を1つのコンポーネントにすれば、各ファイルの可読性が上がるか」という視点で、コンポーネントの分割を行うと良いと思います。

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/App.tsx
> +          {books.map((book) => {
この箇所、Bookコンポーネントを作成したのは非常に良いのですが、ChromeのDev toolsのconsoleを見ると以下のようなエラーが発生しています。
`App.tsx:15 Warning: Each child in a list should have a unique "key" prop.`

このエラーの原因を調べて修正してください。
またその際、「なぜこの記述ではエラーなのか？」という理由も理解できるとより良いです。
Reactの公式のドキュメントでもこのエラーの理由が説明されているので、一度ご自身で調べてみてください。
※次のレビューの際に、参考にしてほしいドキュメントはちゃんと提示します💡

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/App.tsx
> +import type { BookItem } from './types'
型情報のimportの際、`type`キーワードをちゃんと付与しているのは非常に良いです🙆
目的としてはコンパイラに正しい情報を与えるためであり、基本的には「とりあえずつけておいた方が良い」認識で良いと思います。

ちょっとややこしいですが、以下の記事に詳しい理由が書かれているため興味があれば見てみてください。
https://azukiazusa.dev/blog/import-type-from-module/

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/components/Book.tsx
> +import styles from '../App.module.css'
ここはもったいないですね。
せっかくコンポーネントを分けたにも関わらず、`App.tsx`と同じく`App.module.css`をimportしています。

コンポーネントを分割するメリットとして、「責任の分割」というものがあります。
今回のBookコンポーネントであれば、書籍のデータを受け取って書籍に関するUIをレンダリングするというものです。
その場合、そのコンポーネントに関するcssも分割することで可読性やメンテナンス性が向上します。
Bookコンポーネントに関するcssを、別の`*.module.css`に切り分けてみてください。
その場合のファイル名は、何が最適かをその理由とともに考えてみてください💡

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/components/Book.tsx
> +export default Book
このexportの方法を`default export`と呼びます。
一方で例えば9行目を以下のようにする方法を、`named export`と呼びます。
`export const Book = ...`

`default export`の場合、実はimportの際に以下のように全く別の名前をつけてしまうことができます。
`import Magazine from './components/Book'`
※この場合、 JSXで`<Magazine />`として使えてしまいます。

これが`default export`のメリットの1つでもあるのですが、複数人での開発の際は「自由に命名できてしまう」ということが混乱や思わぬ不具合の原因となる場合があります。
そのため基本的には`named export`を使用したほうがいいと思っています。
このコンポーネントも、`named export`を使用するように修正してください。

他にも以下の記事に理由がまとまっているので、参考にしてみてください。
その上でもし、「`default export`を使用したほうがいいんじゃないか？🤔」みたいな意見があれば教えてもらえると嬉しいです🙇
https://zenn.dev/yuji6523/articles/373a675275abc4
https://engineering.linecorp.com/ja/blog/you-dont-need-default-export

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/components/Header.tsx
このコンポーネントも、Bookコンポーネントのコメントを元に修正してみてください💡

2023-10-31 10:38 UTC, NBmaeda commented on booklog/src/App.module.css
> +.boxButton:hover {
細かい指摘にはなりますが、105行目では`a.boxButton`としているにも関わらず`.boxButton:hover `のように要素名が書かれていません。
これもどちらかに統一したほうが好ましいです。

2023-11-02 09:27 UTC, NBphamngocha commented on booklog/src/App.tsx
> +          {books.map((book) => {
@NBmaeda  consoleのエラー確認漏れでした！！申し訳ございません！！

> Key は、どの要素が変更、追加もしくは削除されたのかを React が識別するのに役立ちます。配列内の項目に安定した識別性を与えるため、それぞれの項目に key を与えるべきです。

とReactの公式のドキュメントにて確認してエラーの理由が理解できました！！以降配列があった時、ちゃんと key
を設定するように注意します。

2023-11-02 09:27 UTC, NBphamngocha commented on booklog/src/components/Book.tsx
> +export default Book
@NBmaeda `default export`はデーフォルト設定なのでそのまま使用してしまいました。damさんの仰った通り、`named export`を使用したほうが自由に命名を指定できず一貫性があって、複数人での開発などにはやはり良いですね。勉強になりました！ありがとうございます🙏

2023-11-06 01:39 UTC, NBmaeda approved these changes
ご対応ありがとうございます。指摘した点は全てクリアになっていると思います👏
Step2の実装お疲れ様でした！
引き続きサポートしますので、頑張っていきましょう。

2023-11-06 01:39 UTC, NBmaeda commented on booklog/src/App.tsx
> +          {books.map((book) => {
ご対応ありがとうございます。問題ないと思います👏
すでにご確認されていそうではありますが、以下の公式ドキュメントを読んでもらおうと思っていました。
https://ja.react.dev/learn/rendering-lists

公式ドキュメントを見れば基本的なことはほぼ全て解決すると思いますし、重要な考え方も書いてあります。
ぜひ活用してください。

2023-11-06 01:40 UTC, NBmaeda commented on booklog/src/components/Book.tsx
> +export default Book
一見して分かるとは思いますが、名前付きインポートの場合は`{}`(カーリーブラケット)をつける必要があります。
以下のページなどにも詳しく記載されていますので、興味があればぜひ読んでみてください。
https://jsprimer.net/basic/module/#named-export-import

2023-11-06 03:20 UTC, merged