Step3
NBphamngocha/dept_design_fe_work01 pull request #3
Opened 2023-11-07 09:28 UTC by NBphamngocha

Step3の実装が完了しました。PRをご確認お願いします。
## Issueリンク
https://github.com/newbeescoltd/nb_study_react/issues/6
## Step1のデザイン
http://127.0.0.1:4173/steps/step3/

2023-11-08 05:49 UTC, NBmaeda requested changes
Step3の実装お疲れ様です！
今回の指摘には少し難しい話も含まれています🤯

現時点で全てを理解する必要はないですが、「こういう書き方もあるんだ」「こういう考え方もあるんだ」ということをフワッとでも頭に入れておいてください。
今後学習や業務を進めていく際に振り返って、徐々に理解していけるといいと思っています💡

不明点があればなんでも聞いてください！修正よろしくお願いします🙏

2023-11-08 05:49 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +  let inputRef = useRef("");
本行に関して2点フィードバックがあります。

### 1. `let`の使用に関して

可能な限り`const`を使用するように心がけて、必要な時のみ`let`を使うようにした方が良いです。
理由としては、**`let`は再代入が可能であるためコード全体の俯瞰が難しくなり保守性が悪くなる**からです。
`const`を使用することで**再代入を前提としないコード**を書くことができるため、意図せず保守性が悪いコードを書いてしまうことを避けることができます。

詳しい説明等は[こちら](https://qiita.com/kiyoshiro/items/13c60fad1f5279993fa2)の記事等を参照してください。

### 2. 変数名に関して
一般的に`[name]Ref`という変数名は、DOMへの参照を格納する場合に使用します。
例えば以下のように`input`要素への参照を扱う場合です。
```
let inputRef = useRef<HTMLInputElement>(null);
...
<input ref={inputRef} />
```

余談とはなりますが、`useRef`は上記のように用いられるケースが多いことを覚えておいてください。
その上で今回のように用いるケースもありますが、その場合は変数名を`searchQuery`や`keyword`といった**一見して分かりやすい名前**に変更した方が好ましいです。

またyoshiさんの行っていただいた実装は、`useState`を使っても行うことができます。
`useState`あるいは`useRef`を使用した場合の違いに関して、[こちら](https://zenn.dev/so_nishimura/articles/c7ebfade970bcc)の記事等にまとまっているため参照してみてください。

2023-11-08 05:49 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +          onChange={(e) => (inputRef.current = e.target.value)}
本行に関しても3点フィードバックがあります。

### 1. 引数`e`の型に関して。
19行も併せて、引数`e`がどんな型として推論されているかを確認しておいてください。
最初は見慣れない型かと思いますが、今後よく使うので今のうちに存在を知っておきましょう。


### 2. イベントハンドラとしてアロー関数を渡すことに関して
ちょっと難しい話にはなるため頭の片隅にでも置いておいてください。
イベントハンドラとしてアロー関数を渡すと、[公式ドキュメント](https://legacy.reactjs.org/docs/faq-functions.html#arrow-function-in-render)にも書いてあるとおりパフォーマンスに影響が出る場合があります。

理由としては、コンポーネントの再レンダリングの際に**アロー関数が再生成**されることにより、**厳密な関数の同一性が担保されなくなる**ためです。アロー関数は無名関数なので、こういったことに繋がります。
それを防ぐために、以下のような手法が選択されます。
- `function`キーワードを使って関数宣言を行ったものを、イベントハンドラに渡すことで関数の同一性を担保する。
- `useCallBack`を使用して、再レンダリングの際の関数の再生成を防ぐ。→useCallbackの[公式ドキュメント](https://ja.react.dev/reference/react/useCallback)

少々込み入った話になって理解し難いと思うので、Reactでは「**レンダリング時に起きることを考慮できるか否かでパフォーマンスに差が生まれる**」ということだけフワッと頭に入れておくと、今後の学習の助けになると思います。

### 3. `SyntheticEvent`に関して
「おいなんだそれは」という感じですが、とりあえず「ブラウザのネイティブなイベントを、良い感じに調整してくれるラッパー」という感じで解釈しておいてください。
例えば本行の処理を以下のような関数に切り出すとします。
```
function handleChange(e: React.ChangeEvent<HTMLInputElement>){
  inputRef.current = e.target.value
}
```

この関数`handleChange`を、`onChange={handleChange}`のようにイベントハンドラとして渡しても問題なく動作します。これは、`SyntheticEvent`が自動的にイベントハンドラに渡されるためです。
このようにすれば引数を使用するためにアロー関数を使用する必要がなくなり、パフォーマンスへの影響も考えなくて良さそうです。
`useCallback`を使用するとよりパフォーマンスへの影響を抑えることができますが、ここでは割愛します。

2023-11-08 05:49 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +import { useRef } from "react";
ここは1行にまとめられると思います。コード量に気を配る意識を早めにつけておくと良いと思います💡

2023-11-08 05:49 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +export const SearchBar = (): JSX.Element => {
ここまでの学びをしっかり意識できているのはとても良いですね👍

2023-11-09 10:23 UTC, NBphamngocha commented on booklog/src/components/SearchBar/SearchBar.tsx
> +  let inputRef = useRef("");
@NBmaeda 
ご確認ありがとうございます。
確かに、 letを使うと保守性が悪いでうね。なるべくletをやめてconstを使うように注意します。ただ、確かconstよりletを使いべき場合があるかなって気になっていて、自分で調べた限り[こちら](https://tcd-theme.com/2021/04/javascript-difference-let-const.html#:~:text=let%E3%81%A8const%E3%81%A9%E3%81%A1%E3%82%89%E3%82%92,let%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%BE%E3%81%97%E3%82%87%E3%81%86%E3%80%82)により、

> constでは実装できない変数の再代入が必要なときはletを使用しましょう。
例えばfor文のイテレータにはletを使います。
```
for (let i = 0; i < 3; i++) {
 console.log(i);
}
```

と書いてあります。for文のループの他にletはオススメの場合がありますでしょうか。
（確かにReactではfor文のループよりmapで配列を処理することが多いので、
letを忘れておこうかなと思っておりますが）

useStateあるいはuseRefを使用した場合の違いについても理解しました。
ちなみに、今回の実装にてデータの量が多いため再レンダリングしないようにuseRefを使った方が良い認識であってますでしょうか。どの場合どちらを使用した方が良いのかを自分で判断したいので、ご教授いただけますでしょうか。

2023-11-09 10:23 UTC, NBphamngocha commented on booklog/src/components/SearchBar/SearchBar.tsx
> +          onChange={(e) => (inputRef.current = e.target.value)}
@NBmaeda 
ご確認ありがとうございます。
> functionキーワードを使って関数宣言を行ったものを、イベントハンドラに渡すことで関数の同一性を担保する。

こちらは関数宣言の代わりに例えば以下のように関数式を使ってパフォーマンスには影響を与える可能性がありますでしょうか
```
const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
 return (searchQuery.current = e.currentTarget.value);
};
```

2023-11-10 02:12 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +  let inputRef = useRef("");
ご確認ありがとうございます。良い質問ですね🎉
おっしゃる通り、上記のような`for`ループの変数`i`は`const`キーワードで宣言することができません。再代入できないからですね。
そのため今回の指摘は全く気にせず、`let`を使って良いと思います。

そもそも`let`キーワードが推奨されない理由の1つとして、「再代入が発生する可能性がある」という点があります。
例えば`let foo = "string"`といった記述がある場合、再代入可能であることを前提とすると全ての`foo`に関して「今、どのような値が格納されているか」を意識しなければなりません。
これは例えばグローバル変数など、スコープが大きい場合に問題となります。

そのため、`for`ループではループ内にスコープが限定されていることもあり、そこまで意識する必要はないかと思っています。


また`for`ループの代替手段としては以下があります。
- [for ... of](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of)
- [for ... in](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...in)
- `Array`オブジェクトの[メソッド](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array)

ドキュメントからも分かるように、これらを使用することで`let`を使用しなくてもループ処理を行うことが可能なので見てみてください💡

余談にはなりますが、Reactでは[関数型プログラミング](https://qiita.com/stkdev/items/5c021d4e5d54d56b927c)が採用されることが多いです。
そのため`Array`オブジェクトのメソッドを使用した記述が良く使用されていることも、頭に入れておくと良いと思います。

2023-11-10 02:47 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +          onChange={(e) => (inputRef.current = e.target.value)}
とても細かい話をすると影響を与える可能性はあると[言われています](https://zenn.dev/rgbkids/books/0b75c912d8ac70/viewer/462995#%E3%82%A2%E3%83%AD%E3%83%BC%E9%96%A2%E6%95%B0%E3%81%AF%E3%83%91%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%B3%E3%82%B9%E3%81%8C%E6%82%AA%E3%81%84%E3%81%A8%E8%A8%80%E3%81%86%E3%82%A6%E3%83%AF%E3%82%B5)。ですが個人的には、正直そこまで気にしなくても良いと思っています。
パフォーマンスに与える影響は微々たるものだと思いますし、もっと他の箇所に気を払った方がコード全体は良くなります。
僕はコンポーネントも関数も関数宣言を使用しているのですが、yoshiさんはアロー関数でコンポーネントを宣言しているので統一して`handleChange`もアロー関数で宣言した方がいいかもしれませんね。コード全体の記述方法の統一も重要なポイントです。
ただ、上記の記事のような議論もあるということはぜひ頭に入れておいてください。

それよりも気になる点としては、以下のように`string`を返している点です。
`return (searchQuery.current = e.currentTarget.value);`
代入した結果を返していますが、これは狙ったものでしょうか？🤔
戻り値は`void`でもいいような気がしています。

2023-11-10 07:01 UTC, NBphamngocha commented on booklog/src/components/SearchBar/SearchBar.tsx
> +          onChange={(e) => (inputRef.current = e.target.value)}
@NBmaeda ご教授ありがとうございます。
おしゃった通り、アロー関数でコンポーネントを宣言しているので統一したいので、お聞きしました 😄
パフォーマンスに与える影響がやはりありそうですね。覚えておきます。

> それよりも気になる点としては、以下のようにstringを返している点です。
> return (searchQuery.current = e.currentTarget.value);
> 代入した結果を返していますが、これは狙ったものでしょうか？🤔
> 戻り値はvoidでもいいような気がしています。

アロー関数でコンポーネント宣言すれば、型の指定を忘れてはいけないですね！
このことはやはりアロー関数を使いたいなら、気をつけないといけないポイントですね！

2023-11-10 08:13 UTC, NBphamngocha commented on booklog/src/components/SearchBar/SearchBar.tsx
> +  let inputRef = useRef("");
@NBmaeda 詳しくご説明いただいて、ありがとうございます。

> Reactでは[関数型プログラミング](https://qiita.com/stkdev/items/5c021d4e5d54d56b927c)が採用されることが多いです。

関数型プログラミングという概念と考え方は初耳です！！大変勉強になりました！！

度々すみませんが、useStateとuseRefについてのご質問です。
載っていただいた記事を確認した後、大体useStateとuseRefの違いを理解できましたが、「useRef使用例」の内容はまだやはりわかりづらかったです😭（usePreviousとか聞いたことが無いですね…）
自分で調べてみたら、[こちらの記事](https://choippo.com/react-hook-useref/)が出てきました。それによると、useRefの使い道は以下のように2つがあります。

- DOMを参照するとき
- useRefに値を保持するとき(レンダリングを起こさず値を保持する)

初心者の私にはこの2つの使い道以外覚えておいたほうが良いuseRefの使い道がありますでしょうか。教えていただけますでしょうか。

2023-11-10 09:44 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +  let inputRef = useRef("");
詳しく調べていただいているようで素晴らしいです👏
まだまだReact hooksには慣れていないと思うので、何がなんやらという感じだと思います🫠

ひとまず`usePrevious`に関しては、[useHooks](https://usehooks.com/)というライブラリのカスタムフックなので一旦は無視して大丈夫です！
使用を検討する段階で調べてみるでいいと思います。

>- DOMを参照するとき
>- useRefに値を保持するとき(レンダリングを起こさず値を保持する)

`useRef`に関しては、基本的には上記の使い方を理解できれば問題ないと思います！
それを踏まえて、まずは以下を心がけると良いかもしれません💡
- `useRef`を使用したDOMの参照に慣れる。
- `useState`を使用しない場合に、`useRef`を使用するのか別の方法を取るのかを適切に選択できる。

2023-11-10 09:49 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +          onChange={(e) => (inputRef.current = e.target.value)}
型の指定も大事ですが、要点は「`return`する必要はあるか」という点でした💡
わかりにくい言い回しでしたら申し訳なかったです🙇

これを踏まえて修正を行なってみてください！

2023-11-13 02:31 UTC, NBphamngocha commented on booklog/src/components/SearchBar/SearchBar.tsx
> +import { useRef } from "react";
@NBmaeda こちらに関して、`npm run preview`を実装してstep8が表示されない問題を解決するように削除しました。

2023-11-13 03:27 UTC, NBmaeda requested changes
修正対応をいただきありがとうございます！🙏
あと一歩という感じなので、調整をお願いします。

今回は実装方法自体というより、タイポ等のミスによる修正です。
プログラミングの基本的な視点に立ち返って、着実に対応していきましょう💡

2023-11-13 03:27 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +  const handleChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
関数名が`handleChange`ですが、9行目で定義している関数が`handleOnClick`であることを考えると、`handleOnChange`の方が好ましいです。
関数名を統一することも重要なポイントです。
また一般的な関数の命名ルールも、`handleOn[Event]`を用いるケースが多いと思います。

2023-11-13 03:27 UTC, NBmaeda commented on booklog/src/components/Books/Books .tsx
コンポーネントを分割しているのはとても良いと思います👍
ただ注意すべき点として、ファイル名の中に半角スペースが混じっています。
思わぬバグの温床となりますし、見つけにくいタイポなので避けるようにしましょう。

2023-11-13 04:32 UTC, NBmaeda approved these changes
問題ないと思います。
Step3の実装お疲れ様でした🎉

2023-11-13 05:40 UTC, merged

2023-11-13 11:06 UTC, NBmaeda commented on booklog/src/components/SearchBar/SearchBar.tsx
> +  const handleChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
上記のコメントに関して、訂正させてください🙇

> また一般的な関数の命名ルールも、handleOn[Event]を用いるケースが多いと思います。

上記ですが、改めて考えると一般的なのは`handle[Event]`の方ですね😅
ふと思い返して「あれ？」ってなったので訂正させてもらいます🙇

STEP3のコードはこのままで問題ないですが、STEP4の作業の際にでも`handleChange`と`handleClick`に直しておいてください。
混乱させてしまい、すみませんでした🙇