【FE課題】BooklogのStep2
NBphamngocha/dept_design_fe_work01 pull request #4
Opened 2023-11-15 09:16 UTC by NBphamngocha

Step4の実装が完了しました。PRをご確認お願いします。
## Issueリンク
https://github.com/newbeescoltd/nb_study_react/issues/7
## Step4のデザイン
http://127.0.0.1:4173/steps/step4/

2023-11-16 05:41 UTC, NBmaeda requested changes
step4の実装お疲れ様です！
実装見本から、実装の方向性が導きづらかったと思います。すみません🙇
コメントにて詳細に言及しましたが、タイマー周りの実装を見直しましたのでお手数ですが確認をお願いします🙏

コメントは上記の仕様変更後にも影響がある内容が多いため、それも鑑みて改めて実装をお願いします！

2023-11-16 05:41 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
select要素を触らない状態で「Start」ボタンをクリックした場合、タイマーがスタートしません。
これを改善できるように修正してください。

また非常に申し訳ないのですが、現状の実装見本だと不必要な箇所に気を配る必要があると感じたため、タイマー周りの仕様を見直しました🙇
お手数ですが、改めて[元リポジトリ](https://github.com/newbeescoltd/nb_study_react/tree/main)からpullして新しいstep4の仕様に合わせて実装をお願いします🙏
変更点は以下のような感じです。
- タイマーの終了を、ビジュアルで分かるように変更。
- 秒単位のみのタイマーであるため、不必要な時間・分の表示を削除。

2023-11-16 05:41 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +type TIMES = {
型の名前なのですが、一般的には「[パスカルケース](https://e-words.jp/w/%E3%83%91%E3%82%B9%E3%82%AB%E3%83%AB%E3%82%B1%E3%83%BC%E3%82%B9.html)」で記述されることが多いです。

慣習的なものなので必須ではないですが、全て大文字の「コンスタントケース」は定数等に使用することが多いため、他の作業者がわかりやすいように統一することをお勧めします。

2023-11-16 05:41 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +  const [min, setMin] = useState<TIMES["min"]>(0);
この2行は`useState`を使用する必要はないため、見直した方が良さそうです。
step4のタイマー箇所仕様変更に伴って必然的に削除されるので問題ないとは思いますが、念の為言及しておきます🙇

2023-11-16 05:41 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +  const targetTime = useRef<number>(0);
`useRef`を使用して数字の0で初期化を行なっています。
 VSCodeで確認できると思いますが、この場合`targetTime`の型は`React.MutableRefObject<number>`となります。

名前の通りミュータブル(変更可能)であるため、41行のような再代入が可能となっています。
再代入可能であることのデメリットは以前も話した通りですので今回は省略しますが、それ以外の方法がない場合は避けた方が好ましいです。

今回の使用目的を鑑みると、`React.MutableRefObject<number>`を使用しない方法もありそうです💡
以前のPRで`useRef`に関して言及したことを参照しつつ、他の方法がないかを考えてみてください。

[こちらの記事](https://zenn.dev/berlysia/articles/624bc1aaffda58)には`useRef`の使用の際に気をつけることがまとまっているため、「どうしたらいいか」のセクションだけでも確認してみてください。
だいぶ抽象的な言い方をしてしまったので、不明点や疑問があったらいつでもお待ちしています🤩

2023-11-16 05:41 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +    return () => clearInterval(interval);
ここ、しっかり`return`しているのは素晴らしいですね👏
結構重要なポイントなので、自分の口で「なぜこの行が必要」かを説明できるようにしておきましょう！
もし不明点があれば質問するか、詳しく調べてみてください。

またその上で、22行目の`interval`という変数名を見直してみましょう。
これでもNGではないですが、より分かりやすい変数名もあるため +α の内容として考えてみてください💡

2023-11-16 05:41 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +            onChange={(e: React.ChangeEvent<HTMLSelectElement>) => {
50行目も含め、step3で指摘したことを思い出してみてください。
JSXと関数の実装とを切り分けることで、JSXの可読性やコード全体の見やすさも向上します。

2023-11-20 06:05 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +    return () => clearInterval(interval);
@NBmaeda
こちらの`return`について、自分の口で十分に詳しく説明できないですが、実装した際色々調べてみた上で、[reactホームページからの説明](https://ja.react.dev/reference/react/useEffect#usage)は一番分かりやすかったと思っています。ご共有させていただきます。

> React は必要に応じて`セットアップ関数`と`クリーンアップ関数`を呼び出し、これは複数回行われることがあります。
> 
> コンポーネントがページに追加（マウント）されると、`セットアップコード`が実行されます。
> 依存値が変更された上でコンポーネントが再レンダーされる度に：
> まず、古い props と state で`クリーンアップコード`が実行されます。
> 次に、新しい props と state で`セットアップコード`が実行されます。
> コンポーネントがページから削除（アンマウント）されると、最後に`クリーンアップコード`が実行されます。

というわけで、この`return`は`クリーンアップ関数`として必要だということを理解しております。
もしまだ足りない部分があれば、教えていただければ幸いです🙇‍♀️

2023-11-20 06:24 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +  const targetTime = useRef<number>(0);
@NBmaeda 
ありがとうございます！！とても参考になりました！！
考え直して別の方法で実装してみました。ご確認お願いします🙇‍♀️

2023-11-20 10:16 UTC, NBmaeda requested changes
見本への修正も加味して作業いただき、ありがとうございます🙇

今回は少し修正の分量が多いかつ、内容も複雑なものとなっています😩
JavaScriptやReact hooksを使うにあたって重要なポイントが含まれていますので、少し時間がかかるかもしれませんがしっかり理解できるようにしましょう！

分からない点はいつでも気軽に質問してくださいね！

2023-11-20 10:16 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +      if (ref.current.value) {
この箇所ですが、1行にまとめて書くことができます💡

Optional chainingが各場合においてどのような値を返すか、また`if`文が各値をどのように評価するかを考慮して修正を行なってみてください。

2023-11-20 10:16 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +        setTimer((timer) => (timer -= 1));
[減算代入演算子](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Subtraction_assignment)(`-=`)の使い方に気をつけてください。
`timer -= 1`という式は`timer`自体に`timer - 1`の結果を代入しているため、`timer`を破壊的に変更しています。

ここでは`timer -= 1`を`return`しているだけなので問題はありませんが、以下のような場合を考えてみましょう。`timer`として`5`が渡されるとすると以下のようになります。
```
(timer) => {
    someFunc(timer -= 1) // someFunc(4)が実行される。
    return timer -= 1 // 戻り値として3がreturnされる。
}
```
このようにブロック内で処理が続く場合に引数に対して減算代入演算子を使用すると、その行以降の処理が想定外のものとなる可能性があります。


減算代入演算子を正しく理解しているのであれば、それを使用すべきか、あるいは通常の算術演算子を用いて減算を行うかを適切に判断するようにしましょう。
もし減算代入演算子に対して正しく理解できていないのであれば、この機会にリソースを確認して正しく理解するようにしましょう。

2023-11-20 10:16 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +    }, t);
ここの処理は見直した方が良さそうですね💡
`timer`が更新されるたびに`useEffect`内で起こる処理を考えてみましょう。ざっくり以下のような感じかと思います。
1. クリーンアップ関数が実行され、`interval`と`timeOut`が取り消される。
2. `interval`を宣言し、`setInterval()`の結果を代入。
3. `t`を宣言し、`timer * 1000`の結果を代入。
4. `timeOut`を宣言し、`setTimeout()`の結果を代入。

`setInterval`に渡される関数の内容を見てみると、毎秒ごとに`timer`を更新して新たなインターバルをスタートしています。
`setTimeout`はどうでしょうか。`timer * 1000 ms`後に処理が行われるのですが、`setInterval`の第二引数が`1000`であるため、`timer`が`1`以下にならないと引数として渡す関数が実行されません。
そのため毎回`t`及び`timeOut`が宣言される形になりますが、`timer`が`1`以下の場合以外はこれらはそもそも宣言する必要はありません。
つまり無駄なリソースの消費を毎回行うことになります。

これは`setInterval`関数内で同様の処理を行うことができます。一度考えてみましょう。
useEffectに関しては[公式ドキュメント](https://ja.react.dev/reference/react/useEffect)に詳しく記載があるので、余裕があればぜひ目を通してみてください。

2023-11-20 10:16 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
>      const interval = setInterval(() => {
`setInterval()`に渡す関数内に、`console.log("do interval")`を入れてみましょう。
タイマーを動かしていない時もコンソールに`do interval`が出力されてしまいますね！？😕

これは`timer = 0`になった際の`useEffect()`内の処理にてセットされた`setInterval()`が、以降はクリーンアップされないままインターバル処理を繰り返してしまうためです。
これは想定していない挙動だと思うので、改善のための修正を行いましょう。

2023-11-20 10:16 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +      //intervalのクリアアップ
40行目も同じくですが、「クリアアップ」ではなく「クリーンアップ」です💡
細かい日本語の指摘になってしまい恐縮ですが、この機会に覚えていってください。

2023-11-20 10:16 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +        <p className={`${styles.boxTextTimer} ${isStop && styles.red}`}>
classNameに複数のクラスを指定する方法を理解できていますね👏

しかし、`styles.red`の指定の箇所には注意が必要です。
chromeのdev toolsで確認すると、`isStop = true`の場合以外は`false`というクラスが付与されてしまいます。
これは思わぬ不具合等を引き起こす可能性があるため、修正を行いましょう。

2023-11-20 10:16 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +  const ref = useRef<HTMLSelectElement>(null);
良い`useRef`の使い方だと思います👏
再レンダリングを行わずDOMの値を参照する場合に、`useRef`はよく使用されます。
[この記事](https://ja.legacy.reactjs.org/docs/refs-and-the-dom.html)からリンクされている、新しいドキュメントをぜひ参照してみてください。

2023-11-21 01:33 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +    return () => clearInterval(interval);
上記の内容が理解できていれば大丈夫です！🙆
`useEffect`を使用する際にキモとなる挙動なので、意識してコーディングを行なってください。

2023-11-22 04:09 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
>      const interval = setInterval(() => {
@NBmaeda 
ご指摘ありがとうございます。こちらは自分の反省点です🙇‍♀️

`timer = 0`になった際クリーンアップされないままインターバル処理を繰り返してしまう問題を解決するように`clearInterval(interval)`を追加しました。ただ、ページの最初ロードでは一回setInterval()が実装されていて`console.log("do interval")`がまだ一回確認できました。

原因を調べてみたら、[公式ドキュメント](https://ja.react.dev/reference/react/useEffect)の中に以下が書いてあります。

> [バグを見つけ出すために](https://ja.react.dev/learn/synchronizing-with-effects#step-3-add-cleanup-if-needed)、開発中には React はセットアップとクリーンアップを、セットアップの前に 1 回余分に実行します。これは、エフェクトのロジックが正しく実装されていることを確認するストレステストです。
これは原因だそうので、無視していい認識しておりますが、問題がないでしょうか。

2023-11-22 04:09 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +    }, t);
@NBmaeda 
やり方のよくないところを詳しくご解説していただいて、大変感謝しております（さすがです）🥺

> これはsetInterval関数内で同様の処理を行うことができます。一度考えてみましょう。

ここのヒントのもとに考え直した上で、無駄なリソースになる`t`と`timeOut`の宣言を除いて実装できました🙌
勉強になりました🙏

2023-11-22 07:06 UTC, NBmaeda requested changes
何度も修正対応をいただきありがとうございます🙏
着実に良くなってきていると思います。

今回も細かい指摘が多いですが、あと一息です！
質問があレバいつでも待っていますので、頑張りましょう💪

2023-11-22 07:06 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
>      const interval = setInterval(() => {
@NBphamngocha 
認識通りで大丈夫です👍
しっかり調べていて素晴らしいですね。

useEffectはdev環境で上記のような挙動をするため、今回の件以外でもそれを想定した開発を行うように心がけると良いと思います！

2023-11-22 07:06 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +    if (ref.current?.value !== undefined && ref.current.value) {
この行ですが、結論から言うと以下のように表現することができます。
`if (ref.current?.value) {`

ではなぜ上記のような表現で問題ないのでしょうか。
`if (ref.current?.value !== undefined && ref.current.value)`に関して順を追って考えましょう。
1. `ref.current = null`の場合: [Optional chaining](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining)により、`undefined`が返却されるため`if`ブロック内の文は実行されない。
2. `ref.current?.value === undefined`の場合: `ref.current?.value !== undefined`を満たさないため、`false`となり`if`ブロック内の文は実行されない。
3. `ref.current?.value !== undefined`の場合: `ref.current.value`の型は`string | undefined`であるため、この型は`string`。条件式の`&&`以降が実行されるが、`string`は`true`と評価されるため`if`ブロック内の文が実行される。

3 を考えてみると、`ref.current?.value !== undefined`と`ref.current.value`は等価です。
そのため、以下のように書き換えることができます。
`if (ref.current?.value !== undefined)`

またそもそも`ref.current?.value`自体が`undefined`である場合は`false`と評価されるため、` !== undefined`を行う必要がありません。
そのため、冒頭のような表現にまで省略することが可能です。

条件文は難しいですが、使用している言語で何が`Truthy`あるいは`Falsy`として評価されるのかを意識して、簡潔な表現をするよう心がけてみてください💡

2023-11-22 07:06 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +      if (timer === 1) {
この実装では、23行目も併せると`timer >= 1`の場合を考慮しています。
しかし何らかの遅延や不具合が発生して`setTimer((timer) => timer - 1)`がほぼ同じタイミングで2回続けて発生し、`timer = 0`となってしまった場合はどうでしょうか。
あるいは他のコードで`timer`を変更する処理は必ず無いと絶対に言い切れるでしょうか。(今回は言い切れますが...)

こう言った場合に関して考慮しすぎるのもコードが冗長になる原因ではありますが、今回はこの行を書き換えるだけで`timer`が取り得る値(`number`)すべての場合に関して考慮したコードを完成させることができます。
より良い表現がないかを考えてみてください💡

2023-11-22 07:06 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +        <p className={isStop ? styles.redText : undefined}>
意図した挙動になっていそうですね👏
ただ以下のように、複数の`className`が指定されている場合には注意が必要です。
```<p className={`${styles.boxTextTimer} ${isStop ? styles.redText : undefined}`}>```

この場合は、`<p class="_boxTextTimer_fhf7s_28 undefined">`のようになってしまいます。
せっかくなので、複数の`className`が指定されている場合にこれを回避する方法はないかもぜひ調べて修正してみてください！

2023-11-22 07:06 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +  const [isStop, setIsStop] = useState<boolean>(false);
細かいのですが、この箇所は変数の意味を考えると初期値は`true`の方がふさわしくはないでしょうか🙁
ただそうしてしまうと、ページを開いた瞬間に赤い文字で「読書タイマー 終了」と表示されてしまいます。

初期値が`false`であることに必然性のある、もっと良い変数名はないでしょうか？
変数や関数の名称に必然性のあるものを選択することで、コメントを書く必要がなくなります。
さらには、第三者や将来の自分(1年前に自分が書いたコードはもはや別の人が書いたコードではないですか？😂)にとって、より分かりやすいコードになります。
ぜひ分かりやすく、必然性のある命名を心がけてみてください💡

2023-11-22 07:13 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +      clearInterval(interval);
この箇所ですが、`setInterval`内で`clearInterval`を何の条件もなく使用するのは良い実装ではないと思います。
それであれば`setTimeout`を使用するのとほぼ変わりがないですし、毎度`clearInterval`を実行するのは無駄な処理になるためです。

例えば条件分岐をするなど、より好ましい方法がないかを考えてみましょう。

2023-11-24 03:32 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +    if (ref.current?.value !== undefined && ref.current.value) {
@NBmaeda 
ご説明は詳しくてとても分かりやすかったです！！
お陰様で条件分の奥まで理解してきました💡📝
ステップbyステップで考えながら実装していた私は全体をみて考えるのは今後の改善点ですね😉
ご教授ありがとうございます🙇‍♀️

2023-11-24 03:33 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +      if (timer === 1) {
@NBmaeda 
`timer=0`の時は`読書タイマー 終了`になるから、timer=1までに`setTimer((timer) => timer - 1)`を設定しました。

しかし、damさんの仰った通り、予想外の問題が必ずないわけではないので、`timer=0`の場合もちゃんと踏まえて実装した方が良いですね。ご教授ありがとうございます🙏

もう一度考えた上で、コードを以下のように修正してみました。

```JS
useEffect(() => {
    //intervalのセットアップ
    const interval = setInterval(() => {
      if (timer > 0) {
        setTimer((timer) => timer - 1);
        if (timer === 1) {
          setIsRed(true);
        }
      }
      if (timer === 0) {
        clearInterval(interval);
      }
    }, 1000);
    //intervalのクリーンアップ
    return () => {
      clearInterval(interval);
    };
  }, [timer]);
```
これより良い表現は中々思いつかなくて、参考できるコードとかもしあれば、教えていただけますでしょうか🙇‍♀️
（この後ご指摘いただいた`clearInterval(interval);`の問題も併せてご確認いただければ幸いです🙏）

2023-11-24 03:33 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +  const [isStop, setIsStop] = useState<boolean>(false);
@NBmaeda 

> 細かいのですが、この箇所は変数の意味を考えると初期値はtrueの方がふさわしくはないでしょうか🙁
> ただそうしてしまうと、ページを開いた瞬間に赤い文字で「読書タイマー 終了」と表示されてしまいます。

確かにそうですね😭
一応`const [isTextColorRed, setIsTextColorRed] = useState<boolean>(false);`に変更しましたが、やはりちょっと長い気がしますね。何か良い名称の付け方がありますでしょうか。

2023-11-24 03:55 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +  const [isStop, setIsStop] = useState<boolean>(false);
@NBphamngocha 
命名って難しいですよね...僕も毎回悩むポイントです🥹
Timerの挙動を考えると初期状態では停止していますよね。なので、`isStop`だと初期状態が`true`になってしまいます。

では逆に初期状態が`false`にできるものと考えると、`isStop`の反対の状態を表す変数名であれば良いのではないでしょうか。
例えば`isActive`や`isRunning`であれば、初期状態が`false`であっても問題なさそうです。

こういった変数の命名に関しては、ChatGPTを使用することで効率的に行うことができます。
是非試してみてください💡

2023-11-24 05:13 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +      if (timer === 1) {
@NBphamngocha 
[この記事](https://zenn.dev/uhyo/articles/useeffect-taught-by-extremist#%E6%84%9A%E7%9B%B4%E3%81%AA%E5%AE%9F%E8%A3%85)は、特に`clearInterval`の件に関して参考になると思います💡

では`timer`の値に関しての条件分岐の箇所に関して考えましょう。
以前の修正でのコードを以下に抜粋します。
```
      ...
      if (timer > 1) {
        setTimer((timer) => timer - 1);
      }
      if (timer === 1) {
        setIsStop(true);
      }
      ...
```
このコードであれば`timer > 1`の時しかTimerが作動していないので、`if (timer === 1) {`ではなく`else`や`if (timer <= 1) {`などでも良いと思います。(`else`の方が好ましいですが、後者は条件が分かりにくい時などに明示的に条件を示すために使用しても良いと思います)

今回提示してくれたコードで言うと、以下のような感じですね。`setTimer`されない場合は`isRed = true`でいいと思うので、これで良いと思います。
```
      if (timer > 0) {
        setTimer((timer) => timer - 1);
      }else{
        setIsRed(true);
        clearInterval(interval);
      }
```
ただこれではタイマーが思ったような挙動にならないと思うので、さらに微調整してみてください💡

ポイントとしては、`timer === 1`や`timer <= 1`などの比較演算子の使い分けだと思います。
前者はある瞬間のみの処理を行いたいときに使用し、今回のような「変数がある一定の値以上の時(以外)に行いたい」処理に関しては、後者のような範囲を持った比較演算子を使用した方が良いです。

理解しづらければ、加えて質問等も気軽にしてくださいね！

2023-11-24 08:42 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +      if (timer === 1) {
@NBmaeda 参考記事ありがとうございます！！
 else文を活用して修正してみました。`setIsRed(true);`をelse文中に入れるとテキストは最初から赤いになってしまいますので、以下のように少し調整しました。
```JS
if (timer > 0) {
        setTimer((timer) => timer - 1);
        if (timer === 1) {
          setIsTimeUp(true);
        }
      } else {
        clearInterval(interval);
      }
```

2023-11-24 08:42 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +  const [isStop, setIsStop] = useState<boolean>(false);
@NBmaeda ヒントあるがとうございます👏
そうですね、`isActive`や`isRunning`であれば初期状態が`false`に設定したら第三者にも読んですぐ分かりますね。

ただ、今回のタイマーはちょっとややこしいところがあって、タイマーのテキスト色だけ変更したいので、
例えばすでに週終了したタイマーをリスタートさせる場合`start`ボタンを押したらリスタートの状態(つまり、Active/Runningの状態)になってもこの変数の値をfalseに戻させるですね。なので、少しまだ気が済まないです😢

Google translateの力を借りて、「時間切れる」を翻訳してくれました。「Time is up」だそうですね。
なので、こちらの変数・関数を`const [isTimeUp, setIsTimeUp] = useState<boolean>(false);`に名付けさせていただきます🙇‍♀️

2023-11-24 09:54 UTC, NBmaeda requested changes
修正ありがとうございます！
まだ改善できる点があったので、ご確認・ご対応をお願いします🙏

2023-11-24 09:54 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +            isTimeUp ? " " + styles.redText : ""
いいですね！これであれば不要な`undefined`等が出力されることはありません👏

ただこの行は[テンプレートリテラル](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals)を利用することで、以下のように簡潔に書くことができます。
```isTimeUp ? ` ${styles.redText}` : ""```
是非使用してください。

2023-11-24 09:54 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +        }
前回・前々回のレビューでも言いましたが、何らかの不具合・修正等で`timer`が`1`の際に処理が走らなかった場合`setIsTimeUp`が呼ばれません。
保守性やアプリケーションの堅牢性を高めるためにも、こういった挙動を制御する処理は状態変数`timer`の取りうる値を全てカバーできるようにしましょう。

このケースでは、以下のように修正した方が好ましいです。
```
...
// 24行目 ~ 30行目
if (timer - 1 > 0) {
  setTimer((timer) => timer - 1);
} else {
  setIsTimeUp(true);
  clearInterval(interval);
}
...
```

2023-11-27 09:59 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +        }
@NBmaeda ご教授ありがとうございます。
私の場合は`timer`の初期値は`0`を設定してしまいましたので、
最初から`(timer - 1 > 0)`の条件で timerのstateを変更すると`setIsTimeUp(true)`になってしまいます。
timerの初期値を変更した方が良いですね

2023-11-27 09:59 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +            isTimeUp ? " " + styles.redText : ""
@NBmaeda ご教授ありがとうございます。以下のようにテンプレートリテラルを使ってみましたが、
```JS
className={`boxTextTimer ${isTimeUp ? ` ${styles.redText}` : ""}`}
```
意図通りテキストは赤くならないですが、検証ツールを確認したところ、
<img width="358" alt="スクリーンショット 2023-11-27 18 43 41" src="https://github.com/NBphamngocha/dept_design_fe_work01/assets/128337477/fbfebf56-9020-49d7-9ec5-681c5214516d">
boxTextTimerのclassを確認できてますが、 styles. boxTextTimerの変数ではないと効かなさそうです。

しかも、タイマーが終了する前にboxTextTimerの後ろに白空が入ってしまいます。
<img width="290" alt="スクリーンショット 2023-11-27 18 49 15" src="https://github.com/NBphamngocha/dept_design_fe_work01/assets/128337477/62b6a361-72fc-4683-abef-f5b8d0fae4de">
申し訳ございませんが、ご確認お願いできますでしょうか🙇‍♀️

2023-11-27 10:22 UTC, NBphamngocha commented on booklog/src/components/Header/Header.tsx
> +        }
@NBmaeda 
私の場合は`timer`の初期値は`0`に設定しますので、最初から`(timer - 1 > 0)`の条件で`setTimer`を実装したら、`setIsTimeUp(true)`になってしします。これ全部`if(timer > 0)`に入れると意図通り実装できました。
```JS
if (timer > 0) {
        if (timer - 1 > 0) {
          setTimer((timer) => timer - 1);
        } else {
          setIsTimeUp(true);
          clearInterval(interval);
        }
      }
```

2023-11-28 00:56 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +            isTimeUp ? " " + styles.redText : ""
@NBphamngocha 
```
className={`boxTextTimer ${isTimeUp ? ` ${styles.redText}` : ""}`}
```

1. 
>boxTextTimerのclassを確認できてますが、 styles. boxTextTimerの変数ではないと効かなさそうです。

こちらの問題ですが、上記の表現だと`boxTextTimer`クラスは`class="boxTextTimer"`のように指定している形になります。そのため、CSS Modulesを使用したスタイリングは適用されません。
```className={`${styles.boxTextTimer} ${isTimeUp~```のようにすると解決できると思います。

2.
>しかも、タイマーが終了する前にboxTextTimerの後ろに白空が入ってしまいます。

こちらの問題は`boxTextTimer`と`${isTimeUp`の間に入っている半角スペースが反映されているものです。
```className={`boxTextTimer${isTimeUp~```のようにすると解決できると思います。

上記両方を合わせた表現は、以下のようになります💡
```className={`${styles.boxTextTimer}${isTimeUp~```

2023-11-28 01:40 UTC, NBmaeda commented on booklog/src/components/Header/Header.tsx
> +        }
あるいは以下のようにしても良いかもしれません💡
```
useEffect(() => {
    if(timer <= 0) return;
    const interval = setInterval(() => {
```
これだと`if`のネストが少なくて済みます。

2023-11-28 04:00 UTC, NBmaeda approved these changes
問題ないと思います！
STEP4の完了お疲れ様でした👏

なかなか考えることの多かったSTEPかと思います。
useEffect, useRefの使い方などReact特有のものから、変数名や演算子、falsyな値の扱い方などJavaScriptを含めたプログラミング全般における考え方に関しても扱いました。

しっかり振り返って、少しずつで良いので今後のコーディングに反映していってもらえたらと思います💡

2023-11-28 04:16 UTC, merged