【FE課題】BooklogのStep5
NBphamngocha/dept_design_fe_work01 pull request #5
Opened 2023-12-05 08:42 UTC by NBphamngocha

Step5の実装が完了しました。PRをご確認お願いします。
## Issueリンク
https://github.com/newbeescoltd/nb_study_react/issues/8
## Step4のデザイン
http://127.0.0.1:4173/steps/step5/

2023-12-06 06:57 UTC, NBmaeda requested changes
Step5の作業お疲れ様です！👏
今回からロジック部分が多くなってきて、少し難易度の質が変わったと思います。

レビューの内容としては、主にロジックの内容に関係するものになっています。
JSXやイベント処理の扱い方などは今までの学びを反映して、かなり板についてきたと思うので自信を持ってください🎉
抽象的な指摘もあるので、お気軽に質問お待ちしています！

2023-12-06 06:57 UTC, NBmaeda commented on booklog/src/components/Body/Body.tsx
> +  async function fetchBooksApi(e: SyntheticEvent) {
この関数の引数`e`ですが、使用されていないので削除しても良いと思います。
そうすれば`SyntheticEvent`のimportを削減できます。

2023-12-06 06:57 UTC, NBmaeda commented on booklog/src/components/Body/Body.tsx
> +  const [query, setQuery] = useState<string>("");
`query`の文字列を`useState()`を使って管理しているため、検索ボックスに文字を入力するたびにアプリケーション全体の再レンダリングが走ってしまっています。
これはchromeの[React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=ja)を使用してレンダリングを可視化すると分かりやすいと思います。
導入方法は[こちら](https://dev.classmethod.jp/articles/react-developer-tools/)の記事を参考にしてみてください。

改善方法としては、`useState()`を使用せず`query`を参照できるようにすると良いと思います。
試してみてください。

2023-12-06 06:57 UTC, NBmaeda commented on booklog/src/components/Body/Body.tsx
> +    }
関数の中身は、エラーハンドリングも含め良い感じになっていると思います👏
`fetch()`関数はステータスコードが200以外でもエラーを`throw`しない点は1つポイントになっています。
そのため、20~24行目でしっかりエラーを`throw`するように記述しているのは素晴らしいと思います。

+α の情報としては、ステータスコード別に振り分ける処理が必要な場合は以下の記事のような方法もあることを知っておくと良いと思います。
https://tech.trustbank.co.jp/entry/2023/01/25/091716

2023-12-06 06:57 UTC, NBmaeda commented on booklog/src/components/Body/Body.tsx
> +      setBookItems(bookData.items);
`bookData.items`の型を確認すると`any`になっています。
`bookItems`の型は`BookItem[] | undefined`なので、あまり好ましく無いです。

ここを突き詰めると課題として難しくなりすぎる気はするので今回は省略しますが、APIから取得したデータの型安全性をどう担保するかという意識は持っておいてほしいです。
解決のためには以下のような方法や、ライブラリの利用・スキーマの利用などがあるため、TypeScriptを利用する上で知っておくと良いと思います。
https://zenn.dev/uzimaru0000/articles/json-type-validation

2023-12-06 06:57 UTC, NBmaeda commented on booklog/src/components/Body/SearchBar/SearchBar.tsx
> +    <form className={styles.boxSearchBar} action="#">
ここは`action`属性を指定しなくても大丈夫だと思います💡

2023-12-12 05:18 UTC, NBphamngocha commented on booklog/src/components/Body/Body.tsx
> +      setBookItems(bookData.items);
@NBmaeda ご確認ありがとうございます🙇‍♀️

> bookData.itemsの型を確認するとanyになっています。
> bookItemsの型はBookItem[] | undefinedなので、あまり好ましく無いです。

記事を参考した上で、bookDataのtypeを定義できましたが、やり方は少し違います。
私の場合は`.json()`を分けて実装したので、以下のようにtypeを指定しました。
```JS
const bookData: BooksResult = await response.json();
```
確認してみたところ、`any`になってないですが、この指定方は問題がないかご確認お願いできますでしょうか

後、`JSON にバリデーションをかける`の概念も初耳でした😳💡
今度チャレンジして`Decoder`を使ってみましたが、damさんのおすすめのライブラリ・スキーマジェネレータ（特にasync、await向け）があれば、教えていただけますでしょうか。

2023-12-12 09:03 UTC, NBmaeda commented on booklog/src/components/Body/Body.tsx
> +      setBookItems(bookData.items);
@NBphamngocha 
僕もこのライブラリは使ったことないので詳しいことは言えないのですが、おそらく問題ないと思います！
試しに`items.volumeInfo.title`の型を変えたりしたらちゃんとエラーが出力されていました💡

2023年現在だと[zod](https://github.com/colinhacks/zod)が一番HOTで鮮度の高い情報も多いと思うので、一度見てみてください！

2023-12-12 09:41 UTC, NBmaeda requested changes
修正ありがとうございます！
今回、「json-type-validation」の導入などチャレンジングなことを盛り込んでいただいて素晴らしいと思います👏

一方でケアレスミスなども見られたので、じっくり修正に取り組んでみてください🙏
よろしくお願いします！

2023-12-12 09:41 UTC, NBmaeda commented on booklog/src/components/Body/Body.tsx
> +  const [total, setTotal] = useState<Result["totalItems"]>(0);
21行目も含めVSCode側でエラーが出ているので、ジェネリクスでの型指定が間違っています🤔
指定しようとしている型自体は、共通の型定義から持ってこようとしていて素晴らしいです👏

2023-12-12 09:41 UTC, NBmaeda commented on booklog/src/components/Body/Body.tsx
> +  const ResultDecoder: Decoder<Result> = object({
Decoderの定義は`Body`コンポーネントを定義しているブロックから出しても良さそうですね。
コンポーネント自体の可読性を上げる、という視点も大事にすると分かりやすいコードになります💡

2023-12-12 09:41 UTC, NBmaeda commented on booklog/src/components/Body/Body.tsx
> +  async function fetchBooksApi(query: string): Promise<BooksResult | void> {
関数`fetchBooksApi()`の型注釈を書くのであれば、`Promise<void>`になるかと思います🤔

2023-12-12 09:41 UTC, NBmaeda commented on booklog/src/components/Body/Books/Books.tsx
> +import type { Result, BookItem } from "../../../types";
importする型の名前が間違ってるため、VSCodeでエラーが出てます💡
エラー出てます...よね？

2023-12-12 09:41 UTC, NBmaeda commented on booklog/src/components/Body/Books/Books.tsx
> +            <li key={i} className={styles.boxBook}>
リストの`key`に`index`を使用するのはアンチパターンです😩
https://ja.legacy.reactjs.org/docs/lists-and-keys.html#keys

わざわざこの記述に変更したのは何か意図がある感じですか？

2023-12-12 09:41 UTC, NBmaeda commented on booklog/src/types/index.ts
> -  id: string
`id`を削除してるのは何か意図がある感じですか？

2023-12-13 03:57 UTC, NBphamngocha commented on booklog/src/components/Body/Books/Books.tsx
> +import type { Result, BookItem } from "../../../types";
@NBmaeda 
提出直前修正した内容で、しっかり全てチェックできず申し訳ございません🙇‍♀️
以降注意します！

2023-12-13 03:58 UTC, NBphamngocha commented on booklog/src/components/Body/Books/Books.tsx
> +            <li key={i} className={styles.boxBook}>
@NBmaeda 

> リストのkeyにindexを使用するのはアンチパターンです😩
> https://ja.legacy.reactjs.org/docs/lists-and-keys.html#keys

この前にも指摘していただいたところですね😭

> わざわざこの記述に変更したのは何か意図がある感じですか？

前回のPRを対応した時、色々試して修正した結果`item.id`は読み込まれなくてエラーになったことがあったので、その際 indexを使いました。
後、 `console.log(bookData)`で確認したところ、データが以下のようになりました。

<img width="99" alt="スクリーンショット 2023-12-12 19 02 18" src="https://github.com/NBphamngocha/dept_design_fe_work01/assets/128337477/57b27bda-b8fc-4f1b-a026-ed235d2d8c7b">

ここの 0,1,2...は明確に`id`というkeyを持ってなくておそらくindexではないと思ってました。
確かに、こちらの数字は `id: string`ですね

2023-12-13 08:04 UTC, NBmaeda commented on booklog/src/components/Body/Books/Books.tsx
> +            <li key={i} className={styles.boxBook}>
@NBphamngocha 
なるほど、エラーが起きた際に何か勘違いをしてしまったんですね💡

上記の画像ですが、恐らく`bookItems`を出力したものですかね。
それぞれ配列の`index`及び`id`は以下のようになります。
<img width="317" alt="capture" src="https://github.com/NBphamngocha/dept_design_fe_work01/assets/119549407/d5f513ad-7791-4688-8c1d-619023537950">

> ここの 0,1,2...は明確にidというkeyを持ってなくておそらくindexではないと思ってました。
確かに、こちらの数字は id: stringですね

申し訳ないのですがここの文章の意味が正確に汲み取れず、見当違いのことを言っていたらすみません🙇

2023-12-13 08:06 UTC, NBmaeda approved these changes
修正お疲れ様でした！恐らく問題ないと思います👏
Step5完了おめでとうございます🎉

このStepは少しややこしかったと思いますが、粘り強くチャレンジしてくれて感謝です。
難しいStepが続きますが、引き続き頑張っていきましょう！

2023-12-14 01:56 UTC, NBphamngocha commented on booklog/src/components/Body/Books/Books.tsx
> +            <li key={i} className={styles.boxBook}>
@NBphamngocha 

> 申し訳ないのですがここの文章の意味が正確に汲み取れず、見当違いのことを言っていたらすみません🙇

言葉不足申し訳ございません😭私の言いたいかったことを正しくご理解いただきました！！

> ここの 0,1,2...は明確にidというkeyを持ってなくておそらくindexではないと思ってました。

こちらの言いたかったのは`0,1,2...`は idではなくてindexと思ってたので、
`item.id`を削除してliのkeyにindexを使用しました。
ご説明ありがとうございます！！理解できました😊

2023-12-14 02:01 UTC, merged