【FE課題】BooklogのStep8
NBphamngocha/dept_design_fe_work01 pull request #8
Opened 2024-01-26 09:20 UTC by NBphamngocha

Step8の実装が完了しました。PRをご確認お願いします。

## Issueリンク
https://github.com/newbeescoltd/nb_study_react/issues/29

## Step8の内容
step7で実装した追加・削除機能を、localStorageを利用する形に変更します。
   - チャレンジstepです。可能であればチャレンジしてください。
   - 複数のcomponentで状態を共有できるよう、useContextも使用してみてください。

2024-01-29 04:04 UTC, NBmaeda requested changes
Step8の対応お疲れ様です👏
なかなか難しかったと思いますが、機能的には要件をクリアするものができていて素晴らしいです🎉

ただ1点、`fetchBooksApi`周りのところが設計的に再考しても良いかなと思うので、そこだけ対応をお願いします。
対応の方針等が不明ならいつでも質問ください！
後一歩というところなので、よろしくお願いします💪

2024-01-29 04:04 UTC, NBmaeda commented on booklog/src/components/Body/SideBar/SideBar.tsx
> +  }, [myBooks]);
> [!NOTE]
機能的にはこの場所でも問題ないのですが、個人的にはこのuseEffectは`BooksProvider`の定義箇所に入れています💡
理由としてはmyBooks関連の処理であるため、1つのファイルにまとめることで閲覧性と保守性を上げるためです。

2024-01-29 04:04 UTC, NBmaeda commented on booklog/src/context/index.tsx
> +  async function fetchBooksApi(query: string): Promise<void> {
> [!IMPORTANT]
>これは意見の分かれるところかもしれませんが、個人的には`fetchBooksApi`は`BooksContext`には入れない方が良いと思います💡
>理由としては、この関数はAPIにリクエストして書籍データをfetchするものなのでMyBooksとは直接関係のないものであるためです。
>`fetchBooksApi`をこのファイルで管理した結果として、`total`や`bookItems`といった本来MyBooksとは直接関係のない状態もこのファイルで管理する形となっています。

2024-01-29 04:04 UTC, NBmaeda commented on booklog/src/hooks/index.ts
> +  const [value, setValue] = useState<BookItem[]>(() =>
カスタムフックにして使いまわせるようにしているのは良い工夫ですね🎉

また`useState`の引数のアロー関数、何なのかと思ったら[Lazy initial state](https://legacy.reactjs.org/docs/hooks-reference.html#lazy-initial-state)を利用してるんですね、素晴らしいです👏
これは知らなかったので目から鱗でした👀

2024-01-31 06:58 UTC, NBphamngocha commented on booklog/src/hooks/index.ts
> +  const [value, setValue] = useState<BookItem[]>(() =>
そうですね！私もこの`Lazy initial state`は初耳でした！！

この書き方だと、**遅延初期化**が対応できて初期レンダリング時のみ
`getLocalStorageValue`が呼び出されるので、使ってみました😄

2024-01-31 06:58 UTC, NBphamngocha commented on booklog/src/context/index.tsx
> +  async function fetchBooksApi(query: string): Promise<void> {
@NBmaeda ご確認ありがとうございます。
仰った通り、直接関係のないものを全部一つの contextファイルにまとめてしました…
全体管理には悪いですし、もし誰かコードを確認したい時わかりにくくなりますね😃

わかりやすくなるように、`MyBooksProvider`と`BooksProvider`に分けました。

2024-01-31 09:56 UTC, NBmaeda requested changes
修正ありがとうございます！👏
詳細はコメントに譲りますが、1点気をつけてほしいことがあるため修正をお願いします🙏
後もう一歩なので頑張りましょう！

2024-01-31 09:56 UTC, NBmaeda commented on booklog/src/context/BooksProvider.tsx
まず謝る必要があるのですが、useContextはあまり乱用すべきではないhooksです。
今回学習のために無理やり使用をしたのですが、本来この規模のアプリケーションでは使用する必要のないhooksです。
このことを最初に伝えていなかったこと、すみませんでした🙇
以下で詳細を説明します。

useContextを使用する際のデメリットで以下のようなものがあります。
- コンポーネントがそのContextに依存してしまうため、コンポーネントの再利用性が下がる。
- Contextは実質グローバルステート(アプリケーション全体に影響を及ぼす状態)であるため、Contextへの変更の影響範囲が分かりづらい。

これらのデメリットは、コンポーネントを分割して責任範囲を小さく切り分けることで汎用性と保守性を高めるReactのあり方に、ある種反するものです。
そのためContextの使いすぎには注意する必要があります🚨

その上でこのBooksProviderの必要性を一旦考えてみましょう。
`Body.tsx`, `Books.tsx`, `SideBar.tsx`の3つのファイルでこのContextは使用されていますが、`Books.tsx`, `SideBar.tsx`は`Body.tsx`の直下なので、Contextで管理している状態と関数はpropsにて渡すことができます。

となるとシンプルに`Body.tsx`でこれらの状態を管理すれば良いと思います。
関数は別のファイルに切り出すでも良いですね。(余談ですが、useSearchFormみたいな感じのカスタムフックにするでも良いと思います)

これを元に、Contextは`MyBooksContext`のみを使用する方向で考えてみてください💡

2024-02-02 03:44 UTC, NBphamngocha commented on booklog/src/context/BooksProvider.tsx
@NBmaeda 
確か、直下のコンポーネントにはpropsで管理したら一番わかりやすいので、
`BooksProvider`を使うとやはり逆に複雑になりますね。
理解できました！！詳しくご説明ありがとうございます！！

> (余談ですが、useSearchFormみたいな感じのカスタムフックにするでも良いと思います)

そもそも`fetchBooksApi`関数をBodyからどこか特定のファイルに管理したくてcontextにまとめてしましました。
仰った通り、この関数をカスタマイフックにして使うと`Body.tsx`はスッキリになりますね☺️

余談ではなくアドバイスです！！ありがとうございます🙏

2024-02-02 09:50 UTC, NBmaeda approved these changes
Step8も度重なる修正対応お疲れ様です🙏
そしてFrontend課題完走お疲れ様です！！🎉

良ければ最初の頃のコードを振り返ってみて欲しいのですが、Reactに関してもFrontend Developerとしても成長を感じられるのではないかと思います😌
僕から見ても、yoshiさんはとても成長されたと思います！！

課題のクリアは1つのゴールですが、スタートでもあります。
引き続き、一緒に頑張っていければと思います！よろしくお願いします💪

2024-02-05 03:43 UTC, merged